apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  type: {{ .Values.servicetype }}
  ports:
    - protocol: TCP
      port: {{ .Values.serviceport }}
      targetPort: {{ .Values.containerport }}
      nodePort: {{ .Values.nodeport }}
